import "./globals.css";

import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import { cn } from "../lib/utils"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  channels,
  messages,
  user,
}: Readonly<{
  children: React.ReactNode;
  channels: React.ReactNode;
  messages: React.ReactNode;
  user: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={
        cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )
      }>
        <div>{children}</div>
      </body>
    </html>
  );
}
