/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.26.1
// source: v1.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as v1_pb from './v1_pb'; // proto import: "v1.proto"


export class UsersClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorRegisterUser = new grpcWeb.MethodDescriptor(
    '/Users/RegisterUser',
    grpcWeb.MethodType.UNARY,
    v1_pb.RegisterUserRequest,
    v1_pb.RegisterUserResponse,
    (request: v1_pb.RegisterUserRequest) => {
      return request.serializeBinary();
    },
    v1_pb.RegisterUserResponse.deserializeBinary
  );

  registerUser(
    request: v1_pb.RegisterUserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_pb.RegisterUserResponse>;

  registerUser(
    request: v1_pb.RegisterUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_pb.RegisterUserResponse) => void): grpcWeb.ClientReadableStream<v1_pb.RegisterUserResponse>;

  registerUser(
    request: v1_pb.RegisterUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_pb.RegisterUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Users/RegisterUser',
        request,
        metadata || {},
        this.methodDescriptorRegisterUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Users/RegisterUser',
    request,
    metadata || {},
    this.methodDescriptorRegisterUser);
  }

  methodDescriptorDeleteUser = new grpcWeb.MethodDescriptor(
    '/Users/DeleteUser',
    grpcWeb.MethodType.UNARY,
    v1_pb.DeleteUserRequest,
    v1_pb.DeleteUserResponse,
    (request: v1_pb.DeleteUserRequest) => {
      return request.serializeBinary();
    },
    v1_pb.DeleteUserResponse.deserializeBinary
  );

  deleteUser(
    request: v1_pb.DeleteUserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_pb.DeleteUserResponse>;

  deleteUser(
    request: v1_pb.DeleteUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_pb.DeleteUserResponse) => void): grpcWeb.ClientReadableStream<v1_pb.DeleteUserResponse>;

  deleteUser(
    request: v1_pb.DeleteUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_pb.DeleteUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Users/DeleteUser',
        request,
        metadata || {},
        this.methodDescriptorDeleteUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Users/DeleteUser',
    request,
    metadata || {},
    this.methodDescriptorDeleteUser);
  }

  methodDescriptorGetUserInfo = new grpcWeb.MethodDescriptor(
    '/Users/GetUserInfo',
    grpcWeb.MethodType.UNARY,
    v1_pb.GetUserInfoRequest,
    v1_pb.GetUserInfoResponse,
    (request: v1_pb.GetUserInfoRequest) => {
      return request.serializeBinary();
    },
    v1_pb.GetUserInfoResponse.deserializeBinary
  );

  getUserInfo(
    request: v1_pb.GetUserInfoRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_pb.GetUserInfoResponse>;

  getUserInfo(
    request: v1_pb.GetUserInfoRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_pb.GetUserInfoResponse) => void): grpcWeb.ClientReadableStream<v1_pb.GetUserInfoResponse>;

  getUserInfo(
    request: v1_pb.GetUserInfoRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_pb.GetUserInfoResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Users/GetUserInfo',
        request,
        metadata || {},
        this.methodDescriptorGetUserInfo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Users/GetUserInfo',
    request,
    metadata || {},
    this.methodDescriptorGetUserInfo);
  }

}

